hostname=awsmine.cieh3xdafnrw.us-east-1.rds.amazonaws.com
usuario=admin
passwordencryptado=sBAZjei+APoy7lTbJch07A==
clave=P3MEtPB2wdUXrgoAkrMqEw==
password=Ivannafatima978
database=p3_parcial
puerto=3306
tipoBD=mysql