-- MySQL Script generated by MySQL Workbench
-- Wed Oct  1 00:22:44 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema soft_inv_test
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `soft_inv_test` ;

-- -----------------------------------------------------
-- Schema soft_inv_test
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `soft_inv_test` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `soft_inv_test` ;

-- -----------------------------------------------------
-- Table `soft_inv_test`.`INV_TIPOS_MOVIMIENTOS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `soft_inv_test`.`INV_TIPOS_MOVIMIENTOS` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `soft_inv_test`.`INV_TIPOS_MOVIMIENTOS` (
  `TIPO_MOVIMIENTO_ID` INT NOT NULL,
  `NOMBRE` VARCHAR(45) NOT NULL,
  `DESCRIPCION` VARCHAR(100) NULL,
  `TIPO_OPERACION` ENUM('ENTRADA', 'SALIDA') NOT NULL,
  PRIMARY KEY (`TIPO_MOVIMIENTO_ID`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `soft_inv_test`.`INV_ALMACENES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `soft_inv_test`.`INV_ALMACENES` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `soft_inv_test`.`INV_ALMACENES` (
  `ALMACEN_ID` INT NOT NULL AUTO_INCREMENT,
  `NOMBRE` VARCHAR(45) NOT NULL,
  `ALMACEN_CENTRAL` TINYINT NOT NULL,
  PRIMARY KEY (`ALMACEN_ID`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `soft_inv_test`.`INV_TIPOS_PRODUCTOS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `soft_inv_test`.`INV_TIPOS_PRODUCTOS` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `soft_inv_test`.`INV_TIPOS_PRODUCTOS` (
  `TIPO_PRODUCTO_ID` INT NOT NULL,
  `NOMBRE` VARCHAR(45) NOT NULL,
  `DESCRIPCION` VARCHAR(100) NULL,
  PRIMARY KEY (`TIPO_PRODUCTO_ID`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `soft_inv_test`.`INV_PRODUCTOS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `soft_inv_test`.`INV_PRODUCTOS` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `soft_inv_test`.`INV_PRODUCTOS` (
  `PRODUCTO_ID` INT NOT NULL AUTO_INCREMENT,
  `TIPO_PRODUCTO_ID` INT NOT NULL,
  `NOMBRE` VARCHAR(45) NOT NULL,
  `MARCA` VARCHAR(45) NOT NULL,
  `MODELO` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`PRODUCTO_ID`),
  INDEX `fk_producto_tipo_producto1_idx` (`TIPO_PRODUCTO_ID` ASC) VISIBLE,
  CONSTRAINT `fk_producto_tipo_producto1`
    FOREIGN KEY (`TIPO_PRODUCTO_ID`)
    REFERENCES `soft_inv_test`.`INV_TIPOS_PRODUCTOS` (`TIPO_PRODUCTO_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `soft_inv_test`.`INV_TIPOS_DOCUMENTOS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `soft_inv_test`.`INV_TIPOS_DOCUMENTOS` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `soft_inv_test`.`INV_TIPOS_DOCUMENTOS` (
  `TIPO_DOCUMENTO_ID` INT NOT NULL,
  `NOMBRE` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`TIPO_DOCUMENTO_ID`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `soft_inv_test`.`INV_MOVIMIENTOS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `soft_inv_test`.`INV_MOVIMIENTOS` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `soft_inv_test`.`INV_MOVIMIENTOS` (
  `MOVIMIENTO_ID` INT NOT NULL AUTO_INCREMENT,
  `TIPO_MOVIMIENTO_ID` INT NOT NULL,
  `FECHA_MOVIMIENTO` DATETIME NOT NULL,
  `FECHA_CREACION` DATETIME NOT NULL,
  `TIPO_DOCUMENTO_ID` INT NOT NULL,
  `NUMERO_DOCUMENTO` VARCHAR(45) NOT NULL,
  `ALMACEN_ID` INT NOT NULL,
  `PRODUCTO_ID` INT NOT NULL,
  `CANTIDAD` INT NOT NULL,
  `VALOR` DECIMAL(10,3) NOT NULL,
  PRIMARY KEY (`MOVIMIENTO_ID`),
  INDEX `fk_movimiento_tipo_movimiento1_idx` (`TIPO_MOVIMIENTO_ID` ASC) VISIBLE,
  INDEX `fk_movimiento_almacen1_idx` (`ALMACEN_ID` ASC) VISIBLE,
  INDEX `fk_movimiento_producto1_idx` (`PRODUCTO_ID` ASC) VISIBLE,
  INDEX `fk_movimiento_tipo_documento1_idx` (`TIPO_DOCUMENTO_ID` ASC) VISIBLE,
  CONSTRAINT `fk_movimiento_tipo_movimiento1`
    FOREIGN KEY (`TIPO_MOVIMIENTO_ID`)
    REFERENCES `soft_inv_test`.`INV_TIPOS_MOVIMIENTOS` (`TIPO_MOVIMIENTO_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_movimiento_almacen1`
    FOREIGN KEY (`ALMACEN_ID`)
    REFERENCES `soft_inv_test`.`INV_ALMACENES` (`ALMACEN_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_movimiento_producto1`
    FOREIGN KEY (`PRODUCTO_ID`)
    REFERENCES `soft_inv_test`.`INV_PRODUCTOS` (`PRODUCTO_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_movimiento_tipo_documento1`
    FOREIGN KEY (`TIPO_DOCUMENTO_ID`)
    REFERENCES `soft_inv_test`.`INV_TIPOS_DOCUMENTOS` (`TIPO_DOCUMENTO_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `soft_inv_test`.`INV_PERIODOS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `soft_inv_test`.`INV_PERIODOS` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `soft_inv_test`.`INV_PERIODOS` (
  `ANHO` INT NOT NULL,
  `MES` INT NOT NULL,
  `DESCRIPCION` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ANHO`, `MES`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `soft_inv_test`.`INV_REPORTES_STOCKS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `soft_inv_test`.`INV_REPORTES_STOCKS` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `soft_inv_test`.`INV_REPORTES_STOCKS` (
  `ANHO` INT NOT NULL,
  `MES` INT NOT NULL,
  `PRODUCTO_ID` INT NOT NULL,
  `ALMACEN_ID` INT NOT NULL,
  `SALDO_INICIAL` INT NOT NULL,
  `ENTRADAS` INT NOT NULL,
  `SALIDAS` INT NOT NULL,
  `SALDO_FINAL` INT NOT NULL,
  PRIMARY KEY (`ANHO`, `MES`, `PRODUCTO_ID`, `ALMACEN_ID`),
  INDEX `fk_kardex_producto1_idx` (`PRODUCTO_ID` ASC) VISIBLE,
  INDEX `fk_kardex_almacen1_idx` (`ALMACEN_ID` ASC) VISIBLE,
  CONSTRAINT `fk_kardex_periodo1`
    FOREIGN KEY (`ANHO` , `MES`)
    REFERENCES `soft_inv_test`.`INV_PERIODOS` (`ANHO` , `MES`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_kardex_producto1`
    FOREIGN KEY (`PRODUCTO_ID`)
    REFERENCES `soft_inv_test`.`INV_PRODUCTOS` (`PRODUCTO_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_kardex_almacen1`
    FOREIGN KEY (`ALMACEN_ID`)
    REFERENCES `soft_inv_test`.`INV_ALMACENES` (`ALMACEN_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
