tipo_motor = MYSQL
driver=com.mysql.cj.jdbc.Driver
tipo_de_driver=jdbc:mysql
base_de_datos=transitsoft
nombre_de_host=localhost
#nombre_de_host=database-mysql.chakqsk2m83n.us-east-1.rds.amazonaws.com
puerto=3306
#usuario=admin
usuario=root
contrasenha=0tMQtzZrSWEKwbguoUJrIg==
