tipo_motor = MSSQL
driver=com.microsoft.sqlserver.jdbc.SQLServerDriver
tipo_de_driver=jdbc:sqlserver
base_de_datos=transitsoft
nombre_de_host=database-mssql.cl24m6uiwpw1.us-east-1.rds.amazonaws.com
puerto=1433
usuario=admin
contrasenha=0tMQtzZrSWEKwbguoUJrIg==
